version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    groups:
      test-dependencies:
        patterns:
          - "org.junit*"
          - "org.assertj:*"
          - "io.mockk:*"
          - "org.wiremock:*"
          - "org.testcontainers:*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
