---
version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.2.0
    hostname: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  broker:
    image: confluentinc/cp-kafka:7.2.0
    hostname: broker
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_LOG4J_LOGGERS: 'kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO'

  schema-registry:
    image: confluentinc/cp-schema-registry:7.2.0
    hostname: 'schema-registry'
    depends_on:
      - zookeeper
      - broker
    ports:
      - "8181:8181"
    environment:
      SCHEMA_REGISTRY_LISTENERS: 'https://0.0.0.0:8181'
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: 'PLAINTEXT://broker:29092'
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: 'zookeeper:2181'
      SCHEMA_REGISTRY_HOST_NAME: 'schema-registry'
      SCHEMA_REGISTRY_SSL_KEYSTORE_LOCATION: '/etc/schema-registry/secrets/registry.keystore.jks'
      SCHEMA_REGISTRY_SSL_KEYSTORE_PASSWORD: 'registry'
      SCHEMA_REGISTRY_SSL_KEY_PASSWORD: 'registry'
      SCHEMA_REGISTRY_SSL_TRUSTSTORE_LOCATION: '/etc/schema-registry/secrets/registry.truststore.jks'
      SCHEMA_REGISTRY_SSL_TRUSTSTORE_PASSWORD: 'registry'
      SCHEMA_REGISTRY_SCHEMA_REGISTRY_INTER_INSTANCE_PROTOCOL: 'https'
      SCHEMA_REGISTRY_SCHEMA_REGISTRY_GROUP_ID: 'ssl-group'
      SCHEMA_REGISTRY_KAFKASTORE_TOPIC: '_ssl_schemas'
      SCHEMA_REGISTRY_SSL_CLIENT_AUTHENTICATION: 'REQUIRED'
    volumes:
      - ../../src/integration/resources/secrets:/etc/schema-registry/secrets
