name: "Master"

on:
  push:
    branches:
      - "master"

jobs:
  build:
    name: "Build"
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        kafka_version: [
          "6.2.6",
          "7.2.2",
          "7.3.1",
          "7.6.0"
        ]
    steps:
      - uses: "actions/checkout@v4"
      - uses: "gradle/actions/wrapper-validation@v4"
      - uses: "actions/setup-java@v4"
        with:
          distribution: "temurin"
          java-version: "8"
          cache: "gradle"
      - name: "Build with Gradle"
        env:
          KAFKA_VERSION: ${{ matrix.kafka_version }}
        run: "./gradlew integrationTest"