name: "Master"

on:
  push:
    branches:
      - "master"

jobs:
  build:
    name: "Build"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"
      - uses: "gradle/actions/wrapper-validation@v4"
      - uses: "actions/setup-java@v4"
        with:
          distribution: "temurin"
          java-version: "11"
      - uses: "gradle/actions/setup-gradle@v4"
        with:
          dependency-graph: "generate-and-submit"
      - name: "Build with Gradle"
        env:
          KAFKA_VERSION: ${{ matrix.kafka_version }}
        run: "./gradlew integrationTest"