name: "Master"

on:
  push:
    branches:
      - "master"

jobs:
  build:
    name: "Build"
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        kafka_version: [
          "7.5.9",
          "7.6.0",
          "7.7.4",
          "7.8.3"
        ]
    steps:
      - uses: "actions/checkout@v5"
      - uses: "gradle/actions/wrapper-validation@v5"
      - uses: "actions/setup-java@v5"
        with:
          distribution: "temurin"
          java-version: "17"
      - uses: "gradle/actions/setup-gradle@v5"
        with:
          dependency-graph: "generate-and-submit"
      - name: "Build with Gradle"
        env:
          KAFKA_VERSION: ${{ matrix.kafka_version }}
        run: "./gradlew integrationTest"