name: "Master"

on:
  push:
    branches:
      - "master"

jobs:
  build:
    name: "Build"
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        kafka_version: [
          # This version is KO but probably just a container issue.
          # See https://github.com/testcontainers/testcontainers-java/issues/6423
          # Disabling it for now
          # "5.5.1",

          "6.2.6",
          "7.2.2",
          "7.3.1"
        ]
    steps:
      - uses: "actions/checkout@v3"
      - uses: "gradle/wrapper-validation-action@v1"
      - uses: "actions/setup-java@v3"
        with:
          distribution: "temurin"
          java-version: "8"
          cache: "gradle"
      - name: "Build with Gradle"
        env:
          KAFKA_VERSION: ${{ matrix.kafka_version }}
        run: "./gradlew integrationTest"
