name: "Master"

on:
  push:
    branches:
      - "master"

jobs:
  build:
    name: "Build"
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        kafka_version: [ "5.5.1", "6.2.6", "7.2.1" ]
    steps:
      - uses: "actions/checkout@v2"
      - uses: "gradle/wrapper-validation-action@v1"
      - uses: "actions/setup-java@v2"
        with:
          distribution: "temurin"
          java-version: "8"
          cache: "gradle"
      - name: "Build with Gradle"
        env:
          KAFKA_VERSION: "{matrix.kafka_version}"
        run: "./gradlew build"
