name: "PR"

on: [ "pull_request" ]

jobs:
  build:
    name: "Build"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"
      - uses: "gradle/actions/wrapper-validation@v4"
      - uses: "actions/setup-java@v4"
        with:
          distribution: "temurin"
          java-version: "8"
      - uses: "gradle/actions/setup-gradle@v4"
      - name: "Build with Gradle"
        run: "./gradlew integrationTest --stacktrace"